### ISSUE TITLE
Add custom card.

### ISSUE THREAD

**Issue by Geeky-Sam01** [Geeky-Sam01/omdenaWebPortal#1]
The cards currently present , in the website are not that responsive. 
We need a card that is responsive and has following attributes:
 ```
  Title:
  Paragraph:
  Button: {learn more}
```
### Good to have 👍 :
- using bootstrap or tailwind is a plus.
- Try to add the component card , as a function with parameters so that , we can modify as needed.

**Comment by ishandandekar** [comment]
What will the cards be used for?

**Comment by Geeky-Sam01** [comment]
Not necessary right now.
