### ISSUE TITLE
Replace "Predict" and "Learn more" buttons with Bootstrap buttons 

### ISSUE THREAD

**Issue by Geeky-Sam01** [Geeky-Sam01/omdenaWebPortal#2]
Replace the 'predict' and 'learn more' button in the hero section with Bootstrap button with appropriate colour.

**Comment by ishandandekar** [comment]
Streamlit offers these Button UIs too, is it necessary to use Bootstrap?

**Comment by Geeky-Sam01** [comment]
nope not necessary , but I think making this as a bootstrap button will help us in future to create a bootstrap modal also. For , streamlit buttons to open up a modal (on click) we will need to use something else , that I have to figure out.
